# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatPrivat_pb2 as chatPrivat__pb2


class PrivateChatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMissatge = channel.unary_unary(
                '/PrivateChatsService/EnviarMissatge',
                request_serializer=chatPrivat__pb2.PeticioMissatge.SerializeToString,
                response_deserializer=chatPrivat__pb2.RespostaMissatge.FromString,
                )
        self.RebreMissatges = channel.unary_stream(
                '/PrivateChatsService/RebreMissatges',
                request_serializer=chatPrivat__pb2.Client.SerializeToString,
                response_deserializer=chatPrivat__pb2.Missatge.FromString,
                )


class PrivateChatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnviarMissatge(self, request, context):
        """Servei que proporciona dos procediments per enviar i rebre missatges
        S'utilitza el stream ChatMessage per poder enviar nous missatges al destinatari mentre en rebem d'altre
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebreMissatges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivateChatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMissatge': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMissatge,
                    request_deserializer=chatPrivat__pb2.PeticioMissatge.FromString,
                    response_serializer=chatPrivat__pb2.RespostaMissatge.SerializeToString,
            ),
            'RebreMissatges': grpc.unary_stream_rpc_method_handler(
                    servicer.RebreMissatges,
                    request_deserializer=chatPrivat__pb2.Client.FromString,
                    response_serializer=chatPrivat__pb2.Missatge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrivateChatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrivateChatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarMissatge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateChatsService/EnviarMissatge',
            chatPrivat__pb2.PeticioMissatge.SerializeToString,
            chatPrivat__pb2.RespostaMissatge.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RebreMissatges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PrivateChatsService/RebreMissatges',
            chatPrivat__pb2.Client.SerializeToString,
            chatPrivat__pb2.Missatge.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
