# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hatPrivat.proto\"c\n\x0fPeticioMissatge\x12\x11\n\tid_thread\x18\x01 \x01(\r\x12\x10\n\x08missatge\x18\x02 \x01(\t\x12\x13\n\x0bid_remitent\x18\x03 \x01(\r\x12\x16\n\x0eid_destinatari\x18\x04 \x01(\r\"\x1e\n\x10RespostaMissatge\x12\n\n\x02id\x18\x01 \x01(\x04\"h\n\x08Missatge\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tid_thread\x18\x02 \x01(\r\x12\x10\n\x08missatge\x18\x03 \x01(\t\x12\x13\n\x0bid_remitent\x18\x04 \x01(\r\x12\x16\n\x0eid_destinatari\x18\x05 \x01(\r\" \n\x06\x43lient\x12\x16\n\x0eid_destinatari\x18\x01 \x01(\r2t\n\x13PrivateChatsService\x12\x35\n\x0e\x45nviarMissatge\x12\x10.PeticioMissatge\x1a\x11.RespostaMissatge\x12&\n\x0eRebreMissatges\x12\x07.Client\x1a\t.Missatge0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PETICIOMISSATGE']._serialized_start=20
  _globals['_PETICIOMISSATGE']._serialized_end=119
  _globals['_RESPOSTAMISSATGE']._serialized_start=121
  _globals['_RESPOSTAMISSATGE']._serialized_end=151
  _globals['_MISSATGE']._serialized_start=153
  _globals['_MISSATGE']._serialized_end=257
  _globals['_CLIENT']._serialized_start=259
  _globals['_CLIENT']._serialized_end=291
  _globals['_PRIVATECHATSSERVICE']._serialized_start=293
  _globals['_PRIVATECHATSSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
